version: "3.8"

services:
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - OIDC_CONFIG_URL=https://api.veda.usecustos.org/api/v1/identity-management/.well-known/openid-configuration?client_id=veda-iui65nmkgaf7bihdyndc-10000000
      - CLIENT_ID=veda-iui65nmkgaf7bihdyndc-10000000
    restart: unless-stopped
