version: "3.8"
services:
  jupyterhub:
    build: .
    container_name: jupyterhub-sample
    ports:
      - "8000:8000"
    environment:
      OAUTH_CLIENT_ID: "veda-xxxxx-10000000"
      OAUTH_CLIENT_SECRET: "xxxxxx"
      JUPYTERHUB_CRYPT_KEY: "a99323294a5d6f9b1d0e7e33450dff44db664264231b985e069c6eba8f9a3e09"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
